/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Lawbox Landing API
 * API Spec
 * OpenAPI spec version: 1.0.0
 */

export type CreatedLead = {
  /** Unique identifier of the lead */
  id: number
  /** Confirmation message */
  message: string
}
