/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Lawbox Landing API
 * API Spec
 * OpenAPI spec version: 1.0.0
 */
import type { HealthResponseStatus } from './healthResponseStatus'

export type HealthResponse = {
  /** Liveness status */
  status: HealthResponseStatus
  /** Seconds since process start */
  uptime_s?: number
}
