/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Lawbox Landing API
 * API Spec
 * OpenAPI spec version: 1.0.0
 */

/**
 * Liveness status
 */
export type HealthResponseStatus =
  (typeof HealthResponseStatus)[keyof typeof HealthResponseStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthResponseStatus = {
  ok: 'ok',
} as const
