/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Lawbox Landing API
 * API Spec
 * OpenAPI spec version: 1.0.0
 */

export type NewLead = {
  email: string
  /** @nullable */
  pain_point?: string | null
  /** @nullable */
  firm_size?: string | null
}
